# Generated by Django 3.0.6 on 2020-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200419_2156'),
        ('events', '0003_auto_20200422_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dept_name',
            field=models.ManyToManyField(to='department.Department', verbose_name='Department Name'),
        ),
    ]
