# Generated by Django 3.0.6 on 2020-05-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_remove_lecture_classroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_date',
            new_name='l_date',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_date_end',
            new_name='l_date_end',
        ),
    ]
