# Generated by Django 3.0.5 on 2020-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200422_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image_ads',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Image of Ad'),
        ),
    ]
