# Generated by Django 3.0.6 on 2020-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_classroom_department_name'),
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='classroom_name',
            field=models.ManyToManyField(to='classroom.Classroom', verbose_name='Classroom Name'),
        ),
    ]
