# Generated by Django 3.0.6 on 2020-05-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0003_auto_20200521_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='classroom_name',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='l_name',
        ),
    ]
