# Generated by Django 3.0.5 on 2020-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200419_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(max_length=50, verbose_name='Classroom Name'),
        ),
    ]
