# Generated by Django 3.0.6 on 2020-05-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200419_2156'),
        ('classroom', '0008_auto_20200518_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='department_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='department_name',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='Department Name'),
            preserve_default=False,
        ),
    ]
