# Generated by Django 3.0.6 on 2020-05-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_remove_lecture_classroom_name'),
        ('classroom', '0009_auto_20200518_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lecture_name',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='Lecture Name'),
            preserve_default=False,
        ),
    ]
