# Generated by Django 3.0.6 on 2020-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_classroom_lecture_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=50, unique=True, verbose_name='Lecture Name')),
                ('lecture_date', models.DateTimeField(verbose_name='Lecture Start Date')),
                ('lecture_date_end', models.DateTimeField(verbose_name='Lecture Finish Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_name',
        ),
    ]
