# Generated by Django 3.0.6 on 2020-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_remove_lecture_classroom_name'),
        ('classroom', '0011_auto_20200518_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AddField(
            model_name='classroom',
            name='lecture_name',
            field=models.ManyToManyField(to='lecture.Lecture', verbose_name='lecture name'),
        ),
    ]
