# Generated by Django 3.0.6 on 2020-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200419_2156'),
        ('classroom', '0012_auto_20200518_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='dep_name',
            field=models.ManyToManyField(to='department.Department', verbose_name='Department Name'),
        ),
    ]
