# Generated by Django 3.0.6 on 2020-05-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_remove_lecture_classroom_name'),
        ('classroom', '0013_classroom_dep_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='l_name',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
            preserve_default=False,
        ),
    ]
