# Generated by Django 3.0.6 on 2020-05-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20200519_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_date_end',
        ),
    ]
