# Generated by Django 3.0.6 on 2020-05-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200419_2156'),
        ('classroom', '0024_classroom_departman_ismi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='departman_ismi',
        ),
        migrations.AddField(
            model_name='classroom',
            name='department_name',
            field=models.ManyToManyField(to='department.Department', verbose_name='Department Name'),
        ),
    ]
