# Generated by Django 3.0.6 on 2020-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200419_2156'),
        ('lecture', '0007_auto_20200519_1611'),
        ('student', '0002_auto_20200521_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_name',
            field=models.ManyToManyField(to='department.Department', verbose_name='Department Name'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='lecture_name',
        ),
        migrations.AddField(
            model_name='student',
            name='lecture_name',
            field=models.ManyToManyField(to='lecture.Lecture', verbose_name='lecture_name'),
        ),
    ]
